# For more information: https://laravel.com/docs/sail
version: '3'
services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - '3000:80'
        environment:
            REACT_APP_GRAPHQL_SERVER_URL: http://localhost:4000/graphql
        volumes:
            - 'cra:/usr/share/nginx/html'
        networks:
            - sail
        depends_on:
            - mysql
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        environment:
            APP_SECRET: d8514926303a6e6fe7303770b06e7083
            DB_HOST: localhost
            DB_NAME: misdb
            DB_USERNAME: sysadmin
            DB_PASSWORD: u4=LKc@!k8Mj6WK9
            NODE_ENV: development
            WEB_APP_HOST: http://localhost:80
        volumes:
            - 'nodejs:/usr/src/app'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: u4=LKc@!k8Mj6WK9
            MYSQL_DATABASE: misdb
            MYSQL_USER: sysadmin
            MYSQL_PASSWORD: u4=LKc@!k8Mj6WK9
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mysql:
        driver: local
    cra:
        driver: local
    nodejs:
        driver: local
