version: '3'
services:
    nextjs:
        build:
            dockerfile: Dockerfile
            context: ./techbyte-internal-system-web
        ports:
            - 3000:3000
        volumes:
            - 'nextjs:/usr/src/app'
        networks:
            - app
        depends_on:
            - mysql
    nodejs:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 4000:4000
        environment:
            NODE_ENV: development
            WEB_APP_HOST: http://localhost:3000
            DB_HOST: 127.0.0.1
            DB_USERNAME: techbyte
            DB_PASSWORD: urb@no0202
            DB_NAME: techbytesystem
        volumes:
          - 'nodejs:/usr/src/app'
        networks:
            - app
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        platform: linux/x86_64
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'urb@no0202'
            MYSQL_DATABASE: 'techbytesystem'
            MYSQL_USER: 'techbyte'
            MYSQL_PASSWORD: 'urba@no0202'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mismysql:/var/lib/mysql'
        networks:
            - app
        #healthcheck:
        #  test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        #  retries: 3
        #  timeout: 5s
networks:
    app:
        driver: bridge
volumes:
    mismysql:
        driver: local
    nodejs:
        driver: local
    nextjs:
        driver: local